# We need branch protection rule for all below to have purpose
env:
  PULL_REQUEST_TITLE: "[_MANUAL_] - skip linter"

permissions:
  pull-requests: write

name: "ansible-lint"
on:
  pull_request_target:
    branches:
      - staging
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}

jobs:

  check_pull_requet_title:
    name: "Check pull-request"
    runs-on: ubuntu-latest

    steps:
      - name: "Get info about pull-request"
        id: get_pull-request_info
        uses: actions/github-script@v6
        with:
          script: |
            let isLinterSkipped = false;
            const pullRequests = ( await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.number }} });
            if (pullRequest.data.filter(pr => pr.title.includes('${{ env.PULL_REQUEST_TITLE }}')) { isLinterSkipped = true };
            console.log(isLinterSkipped)

  run_ansible_lint:
    name: "Run ansible-lint"
    runs-on: ubuntu-latest
    needs: ['check_pull_requet_title']
    if: needs.check_pull_requet_title.outputs.isLinterSkipped == 'true'


    steps:
      - name: "Get list of changed files"
        id: get-changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const filesFullList = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.number }}
            });
            const filesNames = filesFullList.data
                .filter(file => file.status !== "removed")
                .map(file => file.filename)
                .join(' ');
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `filesNames=${JSON.stringify(filesNames)}\n`);
            console.log(filesNames)

      - name: "Checkout source branch"
        id: checkout-scm
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Otherwise linter accept list of files as a single filename
      - name: "Remove trailing and leading quotes from list of changed files"
        id: format-filenames
        run: |
          FILENAMES=${{ steps.get-changed-files.outputs.filesNames }}
          FILENAMES="${FILENAMES%\"}"
          FILENAMES="${FILENAMES#\"}"
          echo "FILENAMES=$FILENAMES" >> $GITHUB_ENV

      - name: "Run ansible-lint"
        id: run-lint
        uses: ansible/ansible-lint@main
        with:
          args: ${{ env.FILENAMES }}

      # Add SLACK_API_TOKEN in Github secrets
      - name: "Send Slack notification (fail)"
        id: send-fail-message
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "test_interaction_channel2"
          SLACK_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_MESSAGE: "Ansible-lint has failed! Click Actions URL to see full log."
          SLACK_COLOR: "failure"
          SLACK_USERNAME: "borg-sphere"
          SLACK_ICON: "https://avatars.slack-edge.com/2020-05-22/1133584994822_7ae043ae65db02608c79_512.jpg"
          MSG_MINIMAL: "actions url"
          SLACK_FOOTER: "Powered by borg"

    # Uncomment if logic is desired
      - name: "Close pull request if tests failed"
        id: close-failed-pr
        if: failure()
        uses: actions/github-script@v6
        with:
            script: |
                await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ github.event.number }},
                body: "Pull Request has been closed because it didn't pass tests"
                });
                await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ github.event.number }},
                state: "closed"
                });
