---
# We need branch protection rule for all below to have purpose
env:
  SLACK_CHANNEL: "mig-trash"

concurrency:
  group: ${{ github.workflow }}

name: "ansible-lint"
on:
  workflow_call:
    secrets:
      SLACK_TOKEN:
        description: 'A token passed from the caller workflow'
        required: true

jobs:

  run_ansible_lint:
    name: "Run ansible-lint"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ansible-lint]')}}
    steps:

      - name: "Get list changed files"
        id: get_changed_files
        uses: actions/github-script@v6
        with:
          script: |
            const filesFullList = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.number }}
            });
            const filesNames = filesFullList.data
                .filter(file => file.status !== "removed")
                .map(file => file.filename)
                .join(' ');
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `filesNames=${JSON.stringify(filesNames)}\n`);
            console.log("List of changed files: " + filesNames)

      # Otherwise linter accept list of files as a single filename
      - name: "Remove trailing and leading quotes from list of changed files"
        id: format-filenames
        run: |
          FILENAMES=${{ steps.get_changed_files.outputs.filesNames }}
          FILENAMES="${FILENAMES%\"}"
          FILENAMES="${FILENAMES#\"}"
          echo "FILENAMES=$FILENAMES" >> $GITHUB_ENV

      - name: "Checkout source branch"
        id: checkout-scm
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: "Run ansible-lint"
        id: run-lint
        uses: ansible/ansible-lint@main
        with:
          args: "${{ env.FILENAMES }} >> temp.txt"

      - name:
        id: fail_fail
        if: failure()
        run: |
          echo -e -n "Events==0.5\nImageHash==4.3.1\n" >> ./requirements.txt
          # git --no-pager diff --unified=0 ./requirements.txt
          echo "lines<<EOF" >> $GITHUB_OUTPUT
          echo -n '```' >> $GITHUB_OUTPUT
          cat temp.txt >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # - name: "Fail"
      #   if: success()
      #   run: exit 1

      # Add SLACK_API_TOKEN in Github secrets
      - name: "Send Slack notification (fail)"
        id: send-fail-message
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_CHANNEL }}
            text: ":github-actions:"
            attachments:
              - color: "FF0000"
                fields:
                  - title: "Message"
                    short: false
                    value: "Ansible-lint has failed! Click Actions URL to see full log"
                  - value: "${{steps.fail_fail.outputs.lines}}"
                  - title: "Actions URL"
                    short: false
                    value: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|ansible-lint>"


      # # Uncomment if logic is desired
      # - name: "Close pull request if tests failed"
      #   id: close-failed-pr
      #   if: failure()
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #         await github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: ${{ github.event.number }},
      #         body: "Pull Request has been closed because it didn't pass tests"
      #         });
      #         await github.rest.pulls.update({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: ${{ github.event.number }},
      #         state: "closed"
      #         });
