---
name: "Test Include"

permissions:
  pull-requests: write

on:
  pull_request:  # default event's activity type is opened, synchronize, or reopened
    branches:
      - staging

jobs:
  target_test:
    runs-on: ubuntu-20.04
    steps:
      - name: echo 
        run: |
          echo "HELLO WORLD!"

  call-reusable:
    uses: ./.github/workflows/ansible_linter.yml
