---
name: "Test Include"

permissions:
  pull-requests: write

on:
  pull_request:  # default event's activity type is opened, synchronize, or reopened
    branches:
      - staging

jobs:
  target_test:
    runs-on: ubuntu-20.04
    steps:
      - name: echo 
        run: |
          echo "HELLO WORLD!"
      - name: "Send Slack notification (fail)"
        id: send-fail-message
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_API_TOKEN }}
          payload: |
            channel: "mig-trash"
            text: "Ansible-lint has failed! Click Actions URL to see full log."

  ansible-lint:
    uses: ./.github/workflows/ansible_linter.yml
