# We need branch protection rule for all below to have purpose
name: "Slack message"
on:
  pull_request_target:
    branches:
      - staging


jobs:
  send_message:
    name: "Send slack message"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Send Slack notification"
        id: send-fail-message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "mig-trash"
          SLACK_TOKEN: ${{ secrets.TEST_TOKEN }}
          SLACK_MESSAGE: "It's a test message"
          SLACK_COLOR: "failure"
          SLACK_USERNAME: "borg-sphere"
          SLACK_ICON: "https://avatars.slack-edge.com/2020-05-22/1133584994822_7ae043ae65db02608c79_512.jpg"
          MSG_MINIMAL: "actions url"
          SLACK_FOOTER: "Powered by borg"
