---
name: auto-test

# Need for ansible_lint.yml
permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    branches: [staging, master]


jobs:

  ansible_lint:
    uses: ./.github/workflows/ansible_lint.yml
    secrets:
      SLACK_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
