---
name: "Test Include"

permissions:
  pull-requests: write
  contents: write

on:
  push:  # default event's activity type is opened, synchronize, or reopened
    branches:
      - devel-borg

jobs:
  target_test:
    runs-on: ubuntu-20.04
    steps:
      - name: echo 
        run: |
          echo "HELLO WORLD!"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Push new requirements"
        id: push-new
        env:
          USER_TOKEN: ${{ secrets.SERVICE_USER_TOKEN }}
        run: |
            echo "dddd" >> ./requirements.txt
            git add ./requirements.txt
            git commit -m "[evn] - Updated requirements.txt"
            git push https://x-access-token:${USER_TOKEN}@github.com/${{ github.repository }} HEAD:devel-borg
  # job1:
  #   uses: ./.github/workflows/_execute_test.yml
  #   with:
  #     virtual_env: true
  #     latest_versions: true

  # job2:
  #   runs-on: ubuntu-20.04
  #   needs: job1
  #   steps:
  #     - name: "SHOW"
  #       run:
  #         echo ${{ needs.job1.outputs.requirements}}